name: deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory-be: ./backend
      working-directory-fe: ./frontend
      GS_ID: ${{ secrets.GS_ID }}
      GS_PRIVATE_KEY: ${{ secrets.GS_PRIVATE_KEY }}
      GS_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GS_SERVICE_ACCOUNT_EMAIL }}
      LABBE_DOMAIN: ${{ secrets.LABBE_DOMAIN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install backend dependencies
        run: npm install
        working-directory: ${{ env.working-directory-be }}
      - name: Run tests
        run: npm test
        working-directory: ${{ env.working-directory-be }}
        env:
          CI: true
      - name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: ${{ secrets.SERVER_IP }}
          app-name: "snw"
          git-push-flags: "--force"
